version: "3"

services:
  reverse-proxy:
    image: nginx:alpine
    volumes:
      - ../../reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - udagram-feed-svc
      - udagram-user-svc
    ports:
      - 8080:8080

  udagram-feed-svc:
    build: ../../udagram-feed-api
    container_name: udagram-feed-svc
    env_file:
      - ../../service.env
    volumes: 
      - ${USERPROFILE}/.aws:/root/.aws
    # ports:
    #   - 5002:8080
  
  udagram-user-svc:
    build: ../../udagram-user-api
    container_name: udagram-user-svc
    env_file:
      - ../../service.env
    # volumes: 
    #   - $HOME/.aws:/root/.aws
    # ports:
    #   - 5003:8080

  udagram-frontend-svc:
    build: ../../udagram-frontend
    env_file:
      - ../../service.env
    volumes: 
      - ../../udagram-frontend:/usr/src/app
    depends_on:
      - reverse-proxy
      - udagram-feed-svc
      - udagram-user-svc
    ports:
      - 8100:80
