version: "3"

services:
  reverse-proxy:
    image: nitinallp/reverse-proxy
    depends_on:
      - udagram-feed-api
      - udagram-user-api
    ports:
      - 8080:8080

  udagram-feed-api:
    image: nitinallp/udagram-feed-api
    container_name: udagram-feed-api
    env_file:
      - ../../service.env
    volumes: 
      - ${USERPROFILE}/.aws:/root/.aws
  
  udagram-user-api:
    image: nitinallp/udagram-user-api
    container_name: udagram-user-api
    env_file:
      - ../../service.env

  udagram-frontend-api:
    image: nitinallp/udagram-frontend
    env_file:
      - ../../service.env
    volumes: 
      - ../../udagram-frontend:/usr/src/app
    depends_on:
      - reverse-proxy
      - udagram-feed-api
      - udagram-user-api
    ports:
      - 8100:80
